apiVersion: v1
kind: Pod
metadata:
  name: nginx
# spec:
#   containers:
#   # docker run -d --name nginx nginx
#   - name: nginx
#     image: nginx:stable-perl

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
  containers:
   # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl          values: -gpu
    
  # nodeSelector:
  #   hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
